# Generated by Django 3.0.4 on 2020-04-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('ml', 'Male'), ('fm', 'Female')], default=None, max_length=6)),
                ('email', models.CharField(max_length=50)),
                ('password_first', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'information',
            },
        ),
    ]
